apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spirrel.fullname" . }}
  labels:
    app: {{ include "spirrel.name" . }}
    chart: {{ include "spirrel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "spirrel.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "spirrel.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
          ports:
            - containerPort: 8080
          env:
            - name: ELASTICSEARCH_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "spirrel.fullname" . }}-elasticsearch
                  key: ELASTICSEARCH_HOST
            - name: ELASTICSEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "spirrel.fullname" . }}-elasticsearch
                  key: ELASTICSEARCH_API_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
