apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spirrel.fullname" . }}-elasticsearch
  labels:
    app: {{ include "spirrel.name" . }}
    chart: {{ include "spirrel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  ELASTICSEARCH_HOST: {{ .Values.elasticsearch.host | b64enc | quote }}
  ELASTICSEARCH_API_KEY: {{ .Values.elasticsearch.apiKey | b64enc | quote }}
