replicaCount: 1

image:
  repository: ghcr.io/chazapp/spirrel
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

elasticsearch:
  host: ""
  apiKey: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
